name: terraform plan
on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  plan:
    name: terraform plan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE_ARN_TERRA}}
          role-duration-seconds: 1200

      - name: assume role
        run: aws sts get-caller-identity

      - name: terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - id: init
        run: terraform init
        working-directory: ./terraform

      - id: plan
        run: terraform plan -no-color
        working-directory: ./terraform

      - uses: actions/github-script@0.9.0
        env:
          STDOUT: "```${{ steps.plan.outputs.stdout }}```"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.STDOUT
            })
